from pathlib import Path
import sys

ROOT = Path(__file__).resolve().parents[1]

REQUIRED_PATHS = [
    "README.md",
    "LICENSE",
    ".editorconfig",
    ".gitattributes",
    "docs/ARCHITECTURE.md",
    "docs/QA.md",
    "Packages/manifest.json",
    "ProjectSettings/ProjectVersion.txt",
    "Assets/Scripts/MainScript.cs",
    "Assets/Scripts/MainScriptParts/MainScriptLifecycle.cs",
    "Assets/Scripts/MainScriptParts/MainScriptGameLoop.cs",
    "Assets/Scripts/MainScriptParts/MainScriptSpawning.cs",
    "Assets/Scripts/MainScriptParts/MainScriptLevelFlow.cs",
    "Assets/Scripts/MainScriptParts/MainScriptInput.cs",
    "Assets/Scripts/ChaseCollision.cs",
    "Assets/Scripts/ChaseCollisionParts/ChaseCollisionLifecycle.cs",
    "Assets/Scripts/ChaseCollisionParts/ChaseCollisionAvoidance.cs",
    "Assets/Scripts/Services/LaneLayout.cs",
    "Assets/Scripts/Services/TrafficSpawnPlanner.cs",
    "Assets/Scripts/Services/ChaseLaneDecision.cs",
    "Assets/Scripts/Services/StarTiming.cs",
    "Assets/Tests/EditMode/LaneLayoutTests.cs",
    "Assets/Tests/EditMode/TrafficSpawnPlannerTests.cs",
    "Assets/Tests/EditMode/ChaseLaneDecisionTests.cs",
    "Assets/Tests/EditMode/StarTimingTests.cs",
]

FORBIDDEN_PATHS = [
    "Library",
    "Temp",
    "Obj",
    "Build",
    "Builds",
    "Logs",
    "UserSettings",
]

LINE_LIMITS = {
    "Assets/Scripts/MainScript.cs": 80,
    "Assets/Scripts/MainScriptParts/MainScriptLifecycle.cs": 90,
    "Assets/Scripts/MainScriptParts/MainScriptGameLoop.cs": 140,
    "Assets/Scripts/MainScriptParts/MainScriptSpawning.cs": 80,
    "Assets/Scripts/MainScriptParts/MainScriptLevelFlow.cs": 130,
    "Assets/Scripts/MainScriptParts/MainScriptInput.cs": 60,
    "Assets/Scripts/ChaseCollision.cs": 40,
    "Assets/Scripts/ChaseCollisionParts/ChaseCollisionLifecycle.cs": 40,
    "Assets/Scripts/ChaseCollisionParts/ChaseCollisionAvoidance.cs": 90,
    "Assets/Scripts/Services/LaneLayout.cs": 90,
    "Assets/Scripts/Services/TrafficSpawnPlanner.cs": 70,
    "Assets/Scripts/Services/ChaseLaneDecision.cs": 70,
    "Assets/Scripts/Services/StarTiming.cs": 70,
}

SUSPICIOUS_TERMS = [
    "chat" + "gpt",
    "ai-" + "generated",
    "generated by " + "ai",
    "as an " + "ai",
    "god" + "file",
    "to" + "do",
    "fix" + "me",
    "place" + "holder",
    "dum" + "my",
    "tem" + "plate",
]


def fail(message):
    print(message)
    return 1


def has_comment_syntax(text):
    in_string = False
    in_char = False
    i = 0
    while i < len(text) - 1:
        current = text[i]
        next_char = text[i + 1]

        if in_string:
            if current == "\\":
                i += 2
                continue
            if current == '"':
                in_string = False
        elif in_char:
            if current == "\\":
                i += 2
                continue
            if current == "'":
                in_char = False
        else:
            if current == '"':
                in_string = True
            elif current == "'":
                in_char = True
            elif current == "/" and next_char in {"/", "*"}:
                return True

        i += 1

    return False


def scan_terms(path):
    text = path.read_text(encoding="utf-8", errors="ignore").lower()
    for term in SUSPICIOUS_TERMS:
        if term in text:
            return term

    return None


def main():
    for relative_path in REQUIRED_PATHS:
        if not (ROOT / relative_path).exists():
            return fail(f"Missing required path: {relative_path}")

    for relative_path in FORBIDDEN_PATHS:
        if (ROOT / relative_path).exists():
            return fail(f"Unity output folder should not be committed: {relative_path}")

    for relative_path, max_lines in LINE_LIMITS.items():
        path = ROOT / relative_path
        line_count = len(path.read_text(encoding="utf-8", errors="ignore").splitlines())
        if line_count > max_lines:
            return fail(f"{relative_path} has {line_count} lines; limit is {max_lines}")

    for path in (ROOT / "Assets" / "Scripts").rglob("*.cs"):
        text = path.read_text(encoding="utf-8", errors="ignore")
        if has_comment_syntax(text):
            return fail(f"Comment syntax found in {path.relative_to(ROOT)}")

    for path in (ROOT / "Assets").rglob("*"):
        if path.name.endswith(".meta"):
            continue
        if path.is_dir() or path.suffix.lower() == ".cs":
            meta_path = Path(str(path) + ".meta")
            if not meta_path.exists():
                return fail(f"Missing Unity metadata file: {meta_path.relative_to(ROOT)}")

    scan_roots = [
        ROOT / "README.md",
        ROOT / "docs",
        ROOT / "Assets" / "Scripts",
        ROOT / "Assets" / "Tests",
    ]
    for scan_root in scan_roots:
        paths = [scan_root] if scan_root.is_file() else scan_root.rglob("*")
        for path in paths:
            if path.is_file() and path.suffix.lower() in {".cs", ".md"}:
                term = scan_terms(path)
                if term is not None:
                    return fail(f"Suspicious term '{term}' found in {path.relative_to(ROOT)}")

    return 0


if __name__ == "__main__":
    sys.exit(main())
